### ISSUE TITLE
Parallel pubsub broadcast

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/firenest#13]
`Registry.dispatch` runs in parallel by default. `Phoenix.PubSub` was changed at some point to do the dispatch serially instead of in parallel, should we disable parallel dispatch in firenest by default? Should this even be an option?

**Comment by josevalim** [comment]
Registry defaults to serial I think. The parallel default was a mistake and we reverted on 1.4.1 or 1.4.2.

**Comment by michalmuskala** [comment]
Yes, you're completely right - serial is the default. I must have looked at it incorrectly.
