### ISSUE TITLE
Use the new child_spec definitions

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/firenest#2]
Instead of:

```elixir
supervisor(Firenest.Topology, [MyApp.Topology, adapter: Firenest.Topology.Erlang]),
```

it should be

```elixir
supervisor(Firenest.Topology, [[name: MyApp.Topology, adapter: Firenest.Topology.Erlang]]),
```

To align with the new child_spec coming in Elixir v1.5.

**Comment by frm** [comment]
@josevalim is there any minimum Elixir version Firenest will be supporting? Should we aim for v1.5 minimum, try to keep up with the latest v1.6?

**Comment by josevalim** [comment]
Minimum v1.5 should be enough!

**Comment by frm** [comment]
@josevalim This can be closed, right? :)
