### ISSUE TITLE
broadcast_on_down

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/firenest#3]
Today if a service needs to keep track instances of the same service running on other nodes, they need to monitor those services. However, they can't simply monitor when the node comes up, since the service may not be started yet. So they need to have each service broadcasting messages and start monitoring once they receive the broadcast message. This means we end-up reimplementing the code in the topoogy and monitoring modules.

We can solve this by introducing an idea of broadcast_on_down, where each node monitors an entry locally and automatically broadcasts when the process goes down. This service needs to be part of the topology and we can provide a default implementation in Firenest.Monitor.

**Comment by josevalim** [comment]
I think we can remove the subscribe/unsubscribe/monitor API in favor of this simple callback as long as it also returns the known entries on other nodes for such process.

**Comment by bitwalker** [comment]
To make sure I understand this correctly, if you have nodes A, B, and C, and a service Foo on all three nodes, then `Firenest.Monitor` on each node is responsible for monitoring the local Foo, and then broadcasting to the other nodes when the Foo it is responsible for goes down? I think that makes sense.

I'm less clear on why `subscribe` and `unsubscribe` would be removed though - I thought those were for distributed pub/sub, not monitoring. Or am I overlooking something.

**Comment by josevalim** [comment]
Yes, you understood it correctly. :)

> I'm less clear on why subscribe and unsubscribe would be removed though - I thought those were for distributed pub/sub, not monitoring. Or am I overlooking something.

The reason we have added subscribe and unsubscribe was exactly to implement the monitor functionality. But once we implemented the node functionality, we realized that someone would have to implement subscribe and unsubscribe for services in a node, which is a very similar problem but just a bit of a higher level.

So my intention is to cut up the middleman and provide the subscribe/unsubscribe/monitoring specifically to services.

**Comment by bitwalker** [comment]
Ok, I think I understand what you have in mind, but I'll have to experiment with the API a bit once it's out to grok it fully.

**Comment by josevalim** [comment]
I am tackling this one!

**Comment by josevalim** [comment]
Closing in favor of #8.
